upstream nextjs {
    server moreelektriki-nextjs:3007;
}

server {
    listen 80;
    server_name moreelektriki.ru www.moreelektriki.ru;

    # Проверка доступности для балансировщика
    location /api/health {
        access_log off;
        return 200 "ok";
        add_header Content-Type text/plain;
    }

    # Статические файлы Next.js
    location /_next/ {
        proxy_pass http://nextjs;
        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Все API запросы
    location /api/ {
        proxy_pass http://nextjs;
        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

    # Все остальные запросы
    location / {
        proxy_pass http://nextjs;
        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}